CREATE TABLE IF NOT EXISTS public.curriculos_saas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid DEFAULT gen_random_uuid(),
    identificador text,
    conteudo jsonb,
    UNIQUE (identificador, user_id)
);

ALTER TABLE public.curriculos_saas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Ler proprios curriculos" ON public.curriculos_saas;
CREATE POLICY "Ler proprios curriculos" ON public.curriculos_saas
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Inserir proprios curriculos" ON public.curriculos_saas;
CREATE POLICY "Inserir proprios curriculos" ON public.curriculos_saas
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Atualizar proprios curriculos" ON public.curriculos_saas;
CREATE POLICY "Atualizar proprios curriculos" ON public.curriculos_saas
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Apagar proprios curriculos" ON public.curriculos_saas;
CREATE POLICY "Apagar proprios curriculos" ON public.curriculos_saas
    FOR DELETE USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    full_name text,
    avatar_url text,
    status text NOT NULL DEFAULT 'active',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.user_roles (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'player'::text])),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    UNIQUE (user_id, role)
);

CREATE OR REPLACE FUNCTION public.admin_listar_usuarios()
RETURNS TABLE(id uuid, email character varying, criado_em timestamp with time zone)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.jwt() ->> 'email' != 'dop.jr82@gmail.com' THEN
    RAISE EXCEPTION 'Acesso Negado: Apenas o Administrador pode ver isto.';
  END IF;

  RETURN QUERY SELECT u.id, u.email::varchar, u.created_at FROM auth.users u ORDER BY u.created_at DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_deletar_usuario(alvo_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    admin_email text;
    usuario_email text;
BEGIN
    SELECT email INTO admin_email FROM auth.users WHERE id = auth.uid();
    IF admin_email != 'dop.jr82@gmail.com' THEN
        RAISE EXCEPTION 'Acesso negado.';
    END IF;

    SELECT email INTO usuario_email FROM auth.users WHERE id = alvo_id;

    IF usuario_email NOT LIKE '%_inativo.local' THEN
        UPDATE auth.users SET email = usuario_email || '_inativo.local' WHERE id = alvo_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_reabilitar_usuario(alvo_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    admin_email text;
    usuario_email text;
BEGIN
    SELECT email INTO admin_email FROM auth.users WHERE id = auth.uid();
    IF admin_email != 'dop.jr82@gmail.com' THEN
        RAISE EXCEPTION 'Acesso negado.';
    END IF;

    SELECT email INTO usuario_email FROM auth.users WHERE id = alvo_id;

    IF usuario_email LIKE '%_inativo.local' THEN
        UPDATE auth.users SET email = REPLACE(usuario_email, '_inativo.local', '') WHERE id = alvo_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_excluir_usuario_definitivo(alvo_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    admin_email text;
BEGIN
    SELECT email INTO admin_email FROM auth.users WHERE id = auth.uid();
    IF admin_email != 'dop.jr82@gmail.com' THEN
        RAISE EXCEPTION 'Acesso negado. Apenas o administrador pode excluir contas definitivamente.';
    END IF;

    DELETE FROM auth.users WHERE id = alvo_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.desativar_minha_conta()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE auth.users
  SET email = id::text || '_desativado@inativo.local',
      encrypted_password = 'DISABLED-' || gen_random_uuid()::text
  WHERE id = auth.uid();
END;
$$;
